### ISSUE TITLE
RadParameters and RfluxmtxParameters for Honeybee recipes

### ISSUE THREAD

**Issue by DambronOlivier** [ladybug-tools/honeybee-dynamo#36]
Hi @mostaphaRoudsari ,

When using the sample file of 04_daylight_coefficient_daylight_analysis_Image
I find noise on the render:

![inside_ne_06_21_09](https://cloud.githubusercontent.com/assets/21184323/22174325/7aaf952c-dfd3-11e6-9556-bddef37c793b.png)

I have been trying to set the RfluxmtxParameters as following, though I get an error :
![param](https://cloud.githubusercontent.com/assets/21184323/22174334/cb5d6756-dfd3-11e6-96ea-cdbd96a5d0a0.PNG)

I am not sure how to properly format the parameters for the Rfluxmtx and rcontrib.
Please do let me know if you find some time to share a tip on this matter.

Olivier

**Comment by mostaphaRoudsari** [comment]
@sariths knows better but it's probably because of `samplingRayCounts` aka `-c` which [I set to 3 in the recipe](https://github.com/ladybug-analysis-tools/honeybee/blob/master/honeybee/radiance/recipe/dc/imagebased.py#L190) for the sake of time. We need to create a component for this and let you change the value from Grasshopper.

**Comment by sariths** [comment]
@mostaphaRoudsari is right. This is due to sampling. The graininess is mostly due to sampling. Here is an example of the effect that sampling has on results (the effect is more noticeable in falsecolor images). The white labels with black lettering on the upper-left side of each image correspond to the -c setting. For example, C01 corresponds to -c 1 while C11 corresponds to -c 11. 

![sampling](https://cloud.githubusercontent.com/assets/10361848/22178049/9a127bec-dffa-11e6-87ee-277b1ea8204e.jpeg)

The value set for -c has directly proportional impact on the simulation runtime. There are some additional parameters to consider in case of direct-only calculations. However, that is not relevant in this case.

**Comment by DambronOlivier** [comment]
Hi @sariths,

I have been running various tests with similar C values of  [vwrParaSamp.samplingRaysCount](https://github.com/ladybug-analysis-tools/honeybee/blob/master/honeybee/radiance/recipe/dc/imagebased.py#L190) and [rflux.samplingRaysCount](https://github.com/ladybug-analysis-tools/honeybee/blob/master/honeybee/radiance/recipe/dc/imagebased.py#L222)

In this case with -c 5:
![inside_ne_06_21_11_c05](https://cloud.githubusercontent.com/assets/21184323/22312652/ae20e778-e350-11e6-8db8-984d724b2c27.png)


and here -c 11:
![inside_ne_06_21_11_c11](https://cloud.githubusercontent.com/assets/21184323/22312666/bcf2d914-e350-11e6-9c08-0589c41c1201.png)

Are there other daylightMtxParameters to tune from the Default setting as imagebased.LowQualityImage ?

Olivier

**Comment by sariths** [comment]
Hi @DambronOlivier , there are a couple of other parameters that work in tandem with it..one of them being the limit weight.
Can you please share your gh file with the settings that you are running currently?

**Comment by DambronOlivier** [comment]
@sariths ,
I was using the example file [04_daylight_coefficient_daylight_analysis_Image](https://github.com/ladybug-analysis-tools/honeybee-plus/blob/master/plugin/grasshopper/sampleFiles/04_daylight_coefficient_daylight_analysis_Image.gh)

and modifying my local [imagebased.py](https://github.com/ladybug-analysis-tools/honeybee/blob/master/honeybee/radiance/recipe/dc/imagebased.py)

**Comment by sariths** [comment]
@DambronOlivier , the culprit in this case was the lw (limit weight) parameter....

This is -c 3 -lw 0.001
![selection_114](https://cloud.githubusercontent.com/assets/10361848/22319238/ea745d92-e34e-11e6-8c25-920ceed73264.jpg)

-c 3 -lw 1e-5
![selection_115](https://cloud.githubusercontent.com/assets/10361848/22319261/119a3a5e-e34f-11e6-9573-8610ef735172.jpg)

-c 9 -lw 0.001
![selection_116](https://cloud.githubusercontent.com/assets/10361848/22319272/2342fe08-e34f-11e6-8f0a-a39670138688.jpg)

-c 9 -lw 1e-5
![selection_117](https://cloud.githubusercontent.com/assets/10361848/22319279/37839472-e34f-11e6-9590-ef404169749a.jpg)

A good reference (specifically) for the matrix-based method is Andy McNeil's tutorials on the [Three Phase](https://www.radiance-online.org/learning/tutorials/Tutorial-ThreePhaseMethod.pdf) and [Five Phase Method](https://eetd.lbl.gov/sites/all/files/tutorial-fivephasemethod.pdf). While these documents are not easy to read, they are quite helpful to understand how some of the parameters work.

**Comment by DambronOlivier** [comment]
Thank you very much @sariths .
These tutorials are very useful.

**Comment by mostaphaRoudsari** [comment]
Added the components. We still need to review the input parameters which is an issue for the honeybee repository not here.

![image](https://user-images.githubusercontent.com/2915573/28439443-f1fd3268-6d6f-11e7-993c-79178cf6e9e8.png)
