### ISSUE TITLE
What is the designed testing approach during the development?

### ISSUE THREAD

**Issue by sariths** [ladybug-tools/honeybee-dynamo#4]
HI @mostaphaRoudsari , How do I start adding/test scripts? For all the scripts that I have written for Honeybee (IES) till now, I was working fairly independently of your scripts so I didn't have to import anything other than the folder paths and native Gh or Python components. 

Since that will not be the case here, should I simply code inside the Github /Honeybee-core directory of my computer ?

**Comment by mostaphaRoudsari** [comment]
Hi @sariths,

Yes. The best way that I know is to work on the same code. We can branch out for major developments but for active development right now working on the same code will work fine as far as we commit frequently and keep syncing with the branch before adding, removing stuff.

Since the code is pretty broken down in modules we should not get so many conflicts.

I'm writing a number of test-units for honeybee-core which you can add your own tests to it later. That will also help us to make sure we will catch all the issues and fix them during the development.

For honeybee-grasshopper I started a psudo unit-test script that you can run to make sure all the test grasshopper files are working correctly after the changes. I need to break the big grasshopper file into smaller examples so you can use them as examples. Try to run runTests.py on your machine and you'll see how it works: https://github.com/ladybug-analysis-tools/honeybee-grasshopper/blob/master/test/runTests.py

**Comment by mostaphaRoudsari** [comment]
I think for honeybee we have this mostly figured out however we/I have been lazy in writing unittests. Once the release is out I will be automating the testing process using [Travis CI](https://travis-ci.org/) or a similar service. I leave this issue open for now until we set it up.

**Comment by mostaphaRoudsari** [comment]
Travis integration is now in place both for Ladybug and Honeybee core libraries. Closing this issue.
